export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const CREDENTIAL_SIGN_IN_START = 'CREDENTIAL_SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
